name: Close old issues with the needinfo tag

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Close old issues with the needinfo tag
        uses: dwieeb/needs-reply@71e8d5144caa0d4a1e292348bfafa3866d08c855  # v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-label: needinfo
          close-message: >
            It looks like we haven't heard back on this issue, therefore we are
            closing this issue. If this problem persists in the latest version
            of Thunderbird and the Provider for Google Calendar, please re-open
            this issue.
