# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# Portions Copyright (C) Philipp Kewisch, 2019
---
name: "Release"
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "npm ci"
        run: npm ci

      - if: (github.actor!= 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/') == false)
        name: "Commit lint"
        uses: wagoid/commitlint-github-action@v4

      - name: "ESLint"
        uses: kewisch/action-yet-another-eslint@v1
        with:
          extensions: "js,jsm"

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Build"
        run: npm run build

      - name: "Upload"
        uses: actions/upload-artifact@v2
        with:
          name: gdata-provider.xpi
          path: dist/gdata-provider.xpi

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "npm ci"
        run: npm ci

      - name: "Run Tests"
        run: npm run test

      - name: "Coveralls"
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  sign:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "npm ci"
        run: npm ci

      - name: "Download Build Artifact"
        uses: actions/download-artifact@v2
        with:
          name: gdata-provider.xpi
          path: dist

      - name: "Generate changelog"
        run: npx conventional-changelog -p angular -r 2 | tee dist/CHANGELOG.md

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: dist/gdata-provider.xpi
          channel: listed
          apiUrlPrefix: "https://addons.thunderbird.net/api/v3"
          apiKey: ${{ secrets.ATN_SIGN_KEY }}
          apiSecret: ${{ secrets.ATN_SIGN_SECRET }}

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/gdata-provider.xpi
          body_path: dist/CHANGELOG.md
