# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# Portions Copyright (C) Philipp Kewisch, 2019
---
name: "Release"
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "npm ci"
        run: npm ci

      - name: "ESLint"
        run: npx eslint

      - name: "Build"
        run: npm run build

      - name: "Upload"
        uses: actions/upload-artifact@v4
        with:
          name: gdata-provider.xpi
          path: dist/gdata-provider.xpi

  sign:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "npm ci"
        run: npm ci

      - name: "Download Build Artifact"
        uses: actions/download-artifact@v4
        with:
          name: gdata-provider.xpi
          path: dist

      - name: "Generate changelog"
        run: npx conventional-changelog -p angular -r 2 | tee dist/CHANGELOG.md

# Don't feel comfortable auto-releasing right now due to API keys
#      - name: "web-ext sign"
#        id: web-ext-sign
#        uses: kewisch/action-web-ext@v1
#        with:
#          cmd: sign
#          source: dist/gdata-provider.xpi
#          channel: listed
#          apiUrlPrefix: "https://addons.thunderbird.net/api/v3"
#          apiKey: ${{ secrets.ATN_SIGN_KEY }}
#          apiSecret: ${{ secrets.ATN_SIGN_SECRET }}

      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/gdata-provider.xpi
          body_path: dist/CHANGELOG.md
